//import type { Metadata } from "next";
//import { Inter } from "@next/font/google";
import { Metadata } from 'next';
import "./globals.css";
import styles from './layout.module.css'
import Link from 'next/link';
//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title:'product site',
  description:' we sell products',
  icons:{
    icon:'/favicon.ico'
  }

}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
        <header className={styles.header}>
          <h1>Demo Note App</h1>
          <nav className={styles.nav}>
            <Link href='/products'>Products</Link>
            <Link href='/about'>About</Link>
            <Link href='/contact'>Contact</Link>
          </nav>
        </header>
        {children}
  </>
  
  );
}
