//import type { Metadata } from "next";
//import { Inter } from "@next/font/google";
//import "./globals.css";
import styles from './layout.module.css'
import Link from 'next/link';
import { Metadata } from 'next';
//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
    title:'product site - check all products!',
    description:' we sell products',
    icons:{
      icon:'/favicon.ico'
    }
  
  }

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <>
       
          <nav className={styles.nav}>
            <Link href='/products/women'>여성옷</Link>
            <Link href='/products/men'>남성옷</Link>
          </nav>
        <section className={styles.product}>{children}</section>
          
        
    </>

  );
}
